@startwbs maven_tree
*[#FFFFEE] Place where your code lives
** "my-project"
***_ pom.xml
***[#CCFFFF] parent
****_ pom.xml
***[#FFCCCC]< service1
****_ pom.xml
***[#CCFFCC]< library1
****_ pom.xml

***[#CCFFCC] library2
****_ pom.xml

***[#FFCCCC] service2
****_ pom.xml
@endwbs
