@startuml nosqlschema

entity "Customer" {
  * id
  --
  name
  email
  address
}

entity "Product" {
  * id
  --
  name
  description
  price
}

entity "Order" {
  * id
  --
  * customer_id <<FK>>
  date
}

entity "OrderItem" {
  * id
  --
  * order_id <<FK>>
  * product_id <<FK>>
  quantity
}

Customer }|-- Order
Order }|-- OrderItem
Product }|-- OrderItem

@enduml