@startjson order example
{
        "id": 123,
        "date": "2019-01-01",
        "address": "3rd rock from the sun",
        "customer": {
            "id": 456,
            "name": "John Doe"
        },
        "items": [
            {
                "id": 789,
                "name": "light saber",
                "quantity": 2,
                "price": 10.00
            },
            {
                "id": 101,
                "name": "Force training manual",
                "quantity": 1,
                "price": 20.00
            }
        ]
    }
@endjson