@startuml ChunkedSequence
start
while (chunks coming in)
:chunk arrives;
:convert to text;
note left: TextDecoderStream
:extract JSON strings;
note left: TransformStream
:convert to JSON object;
note left: TransformStream
:process JSON object;
note left: WritableStream
endwhile
stop
@enduml