@startuml OAuthDance
autonumber
title OAuth Flow
actor       "User" as human
participant "Service provider" as App
participant "OAuth\nAuthorization\nEndpoint" as OAuth1
participant "OAuth\nToken\nEndpoint" as OAuth2
participant "Identity Provider" as IdP
database "KEEP API\nEndpoint" as keep
human -> App: request resource
human <-- App: request\nauthorization
human -> OAuth1: access OAuth
OAuth1 --> IdP: redirect to Authentication
human <-> IdP: authenticates
human -> OAuth1: authorizes client\nfor registered scopes
human <-- OAuth1: redirects with authorization code
human -> App: provide authorziation code
App -> OAuth2: send client id\nand authorization code
App <- OAuth2: provide access token (JWT)
App -[#000000]> keep: send access token (JWT) with resource request
App <[#000000]- human: provide resource
@enduml