# This is a draft for an online/mobile banking
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Mobile Banking
  description: Securely acccess banking through an online API
  version: "0.0.1"
# the domain of the service
host: futurebank.dragontamer.net
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
consumes:
  - application/json
paths:
  /accounts:
    get:
      summary: List of accounts
      description: |
        List of accounts the authenticated user has access to.<br />
        Includes account number, name, balance and ledger balance
      tags:
        - Account
      responses:
        200:
          description: An array of accounts in no specific order
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /approvals:
    get:
      summary: Pending approvals
      description: List of transactiosn the current authenticated user needs to approve. When the account is specified limited to that account, otherwise all of them
      parameters:
        - name: account
          in: query
          type: string
          description: Account to limit the list of 
      tags:
        - Approvals
      responses:
        200:
          description: An array of transactions pending approval
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      tags:
        - Approvals
      summary: Record a new approval decision
      description: "Approval can be approve or reject. Decision is captured with a digital signature"
      operationId: addApproval
      parameters:
        - in: body
          name: body
          description: Transaction object including approval information JSON signed
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: Transaction approval accepted   
        "405":
          description: Invalid input           
  /me:
    get:
      summary: User Profile
      description: The User Profile endpoint returns information about the user that has authorized with the application.
      tags:
        - User
      responses:
        200:
          description: Profile information for a user
          schema:
            $ref: '#/definitions/Profile'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /history:
    get:
      summary: User Activity
      description: The User Activity endpoint returns data about a user's lifetime activity with the bank. The response will include new transactions and approval results.<br><br>The history array in the response will have a maximum length based on the limit parameter. The response value count may exceed limit, therefore subsequent API requests may be necessary.
      parameters:
        - name: offset
          in: query
          type: integer
          format: int32
          description: Offset the list of returned results by this amount. Default is zero.
        - name: limit
          in: query
          type: integer
          format: int32
          description: Number of items to retrieve. Default is 5, maximum is 100.
      tags:
        - User
      responses:
        200:
          description: History information for the given user
          schema:
            $ref: '#/definitions/Activities'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Account:
    properties:
      account_id:
        type: string
        description: Unique identifier representing a specific account. Typically numeric, but might contain slashed, dasheds dots. Unique to the bank.
      account_name:
        type: string
        description: Alpha numeric description of the account
      currency_code:
        type: string
        description: "[ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code."
      balance:
        type: number
        description: Current account balance
      ledger:
        type: number
        description: Ledger balance of the account
      #TODO: add approver information here
                
  Transaction:
    properties:
      account_id:
        type: string
        description: Account the transaction
      currency_code:
        type: string
        description: "[ISO 4217](http://en.wikipedia.org/wiki/ISO_4217) currency code."
      description:
        type: string
        description: What the transaction is about
      amount:
        type: number
        description: Transaction amount
      date_requested:
        type: string
        description: date transaction was - requested ISO date
      approval:
        type: object
        description: Approval information including approver and digital signature eventually
        $ref: '#/definitions/Approval'
  Approval:
     properties:
       approval_date:
         type: string
         description: When was the approval generated - ISO date
       approver:
         type: string
         description: Name of the approver as in the profile
         #TODO: should we have an ID instead of a name?
       status:
         type: string
         description: Status of the approval - undecided, approved, rejected   
       fingerprint:
         type: string
         description: Digital signature of the whole transaction to be able to verify transaction integrity           
  Profile:
    properties:
      first_name:
        type: string
        description: First name.
      last_name:
        type: string
        description: Last name.
      email:
        type: string
        description: Email address.
      picture:
        type: string
        description: Image URL of the user.
        #TODO add account authorization info here
  Activity:
    properties:
      uuid:
        type: string
        description: Unique identifier for the activity
  Activities:
    properties:
      offset:
        type: integer
        format: int32
        description: Position in pagination.
      limit:
        type: integer
        format: int32
        description: Number of items to retrieve (100 max).
      count:
        type: integer
        format: int32
        description: Total number of items available.
      history:
        type: array
        items:
          $ref: '#/definitions/Activity'
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
